### PR TITLE
Nate/audio

### PR DESCRIPTION
**Pull request by yradsmikham**
Refined and added Jupyter notebook (v1)
Included Enabling GPU Device in Readme
Added .gitignore

### CODE REVIEW

**Comment by NathanielRose** [comment]
@yradsmikham 
Nice! A few things:
- Can you provide instructions for users to check if they have GPU  enabled in the Enabling GPU Device section
- Issues with nvidia-docker on my machine. Any thoughts on how to fix?
``` 
adminrose@foxds:~/fox/foxAudio/models/research/audioset$ sudo apt-get install nvidia-docker2
Reading package lists... Done
Building dependency tree
Reading state information... Done
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 cuda-libraries-dev-10-0 : Depends: cuda-nvgraph-dev-10-0 (>= 10.0.130) but it is not going to be installed
 cuda-toolkit-10-0 : Depends: cuda-samples-10-0 (>= 10.0.130) but it is not going to be installed
                     Depends: cuda-documentation-10-0 (>= 10.0.130) but it is not going to be installed
 cuda-tools-10-0 : Depends: cuda-visual-tools-10-0 (>= 10.0.130) but it is not going to be installed
 nvidia-docker2 : Depends: nvidia-container-runtime (= 2.0.0+docker18.06.1-1) but 2.0.0+docker18.03.1-1 is to be installed
                  Depends: docker-ce (= 18.06.1~ce~3-0~ubuntu) but 18.03.1~ce-0~ubuntu is to be installed or
                           docker-ee (= 18.06.1~ee~3-0~ubuntu) but it is not installable
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
adminrose@foxds:~/fox/foxAudio/models/research/audioset$ apt-get -f install
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?
adminrose@foxds:~/fox/foxAudio/models/research/audioset$ cd /
adminrose@foxds:/$ apt-get -f install
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?
adminrose@foxds:/$ sudo apt-get -f install
Reading package lists... Done
Building dependency tree
Reading state information... Done
Correcting dependencies... Done
The following additional packages will be installed:
  cuda-documentation-10-0 cuda-nsight-compute-10-0 cuda-nvgraph-dev-10-0 cuda-samples-10-0 cuda-visual-tools-10-0
The following NEW packages will be installed:
  cuda-documentation-10-0 cuda-nsight-compute-10-0 cuda-nvgraph-dev-10-0 cuda-samples-10-0 cuda-visual-tools-10-0
0 upgraded, 5 newly installed, 0 to remove and 33 not upgraded.
52 not fully installed or removed.
Need to get 0 B/728 MB of archives.
After this operation, 1,544 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
(Reading database ... 464297 files and directories currently installed.)
Preparing to unpack .../cuda-nvgraph-dev-10-0_10.0.130-1_amd64.deb ...
Unpacking cuda-nvgraph-dev-10-0 (10.0.130-1) ...
dpkg: error processing archive /var/cache/apt/archives/cuda-nvgraph-dev-10-0_10.0.130-1_amd64.deb (--unpack):
 cannot copy extracted data for './usr/local/cuda-10.0/targets/x86_64-linux/lib/libnvgraph_static.a' to '/usr/local/cuda-10.0/targets/x86_64-linux/lib/libnvgraph_static.a.dpkg-new': failed to write (No space left on device)
No apport report written because the error message indicates a disk full error
                                                                              dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Preparing to unpack .../cuda-nsight-compute-10-0_10.0.130-1_amd64.deb ...
Unpacking cuda-nsight-compute-10-0 (10.0.130-1) ...
dpkg: error processing archive /var/cache/apt/archives/cuda-nsight-compute-10-0_10.0.130-1_amd64.deb (--unpack):
 cannot copy extracted data for './usr/local/cuda-10.0/NsightCompute-1.0/target/linux-desktop-glibc_2_11_3-glx-x64/libnvperf_host.so' to '/usr/local/cuda-10.0/NsightCompute-1.0/target/linux-desktop-glibc_2_11_3-glx-x64/libnvperf_host.so.dpkg-new': failed to write (No space left on device)
No apport report written because the error message indicates a disk full error
                                                                              dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Preparing to unpack .../cuda-visual-tools-10-0_10.0.130-1_amd64.deb ...
Unpacking cuda-visual-tools-10-0 (10.0.130-1) ...
dpkg: error processing archive /var/cache/apt/archives/cuda-visual-tools-10-0_10.0.130-1_amd64.deb (--unpack):
 cannot copy extracted data for './usr/local/cuda-10.0/libnvvp/plugins/org.eclipse.cdt.core_5.7.0.nvidia-qualifier.jar' to '/usr/local/cuda-10.0/libnvvp/plugins/org.eclipse.cdt.core_5.7.0.nvidia-qualifier.jar.dpkg-new': failed to write (No space left on device)
No apport report written because the error message indicates a disk full error
                                                                              dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Preparing to unpack .../cuda-samples-10-0_10.0.130-1_amd64.deb ...
Unpacking cuda-samples-10-0 (10.0.130-1) ...
dpkg: error processing archive /var/cache/apt/archives/cuda-samples-10-0_10.0.130-1_amd64.deb (--unpack):
 cannot copy extracted data for './usr/local/cuda-10.0/samples/3_Imaging/bicubicTexture/data/4_catmull-rom.ppm' to '/usr/local/cuda-10.0/samples/3_Imaging/bicubicTexture/data/4_catmull-rom.ppm.dpkg-new': failed to write (No space left on device)
No apport report written because MaxReports is reached already
                                                              dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Preparing to unpack .../cuda-documentation-10-0_10.0.130-1_amd64.deb ...
Unpacking cuda-documentation-10-0 (10.0.130-1) ...
dpkg: error processing archive /var/cache/apt/archives/cuda-documentation-10-0_10.0.130-1_amd64.deb (--unpack):
 cannot copy extracted data for './usr/local/cuda-10.0/doc/html/npp/group__image__sub.html' to '/usr/local/cuda-10.0/doc/html/npp/group__image__sub.html.dpkg-new': failed to write (No space left on device)
No apport report written because MaxReports is reached already
                                                              dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/cuda-nvgraph-dev-10-0_10.0.130-1_amd64.deb
 /var/cache/apt/archives/cuda-nsight-compute-10-0_10.0.130-1_amd64.deb
 /var/cache/apt/archives/cuda-visual-tools-10-0_10.0.130-1_amd64.deb
 /var/cache/apt/archives/cuda-samples-10-0_10.0.130-1_amd64.deb
 /var/cache/apt/archives/cuda-documentation-10-0_10.0.130-1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
adminrose@foxds:/$ sudo apt-get install nvidia-docker2
Reading package lists... Done
Building dependency tree
Reading state information... Done
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 cuda-libraries-dev-10-0 : Depends: cuda-nvgraph-dev-10-0 (>= 10.0.130) but it is not going to be installed
 cuda-toolkit-10-0 : Depends: cuda-samples-10-0 (>= 10.0.130) but it is not going to be installed
                     Depends: cuda-documentation-10-0 (>= 10.0.130) but it is not going to be installed
 cuda-tools-10-0 : Depends: cuda-visual-tools-10-0 (>= 10.0.130) but it is not going to be installed
 nvidia-docker2 : Depends: nvidia-container-runtime (= 2.0.0+docker18.06.1-1) but 2.0.0+docker18.03.1-1 is to be installed
                  Depends: docker-ce (= 18.06.1~ce~3-0~ubuntu) but 18.03.1~ce-0~ubuntu is to be installed or
                           docker-ee (= 18.06.1~ee~3-0~ubuntu) but it is not installable
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
adminrose@foxds:/$ nvidia-docker run --rm nvidia/cuda nvidia-smi
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.37/containers/create: dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.
adminrose@foxds:/$ sudo nvidia-docker run --rm nvidia/cuda nvidia-smi
Unable to find image 'nvidia/cuda:latest' locally
latest: Pulling from nvidia/cuda
124c757242f8: Pull complete
9d866f8bde2a: Pull complete
fa3f2f277e67: Pull complete
398d32b153e8: Pull complete
afde35469481: Pull complete
2daa37007a29: Pull complete
5499acc0a3fa: Pull complete
3510706284f2: Pull complete
c7aca7b79a5d: Pull complete
Digest: sha256:ccd45db16ba6c3236cedde93120d16cd12163e95f337450414ecd022b489ac84
Status: Downloaded newer image for nvidia/cuda:latest
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:385: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=10.0 brand=tesla,driver>=384,driver<385 --pid=14295 /data/docker/overlay2/f103649803b8b89b7934bfa969c004e5c67374ed60d00b3951cf116f0f8881f0/merged]\\\\nnvidia-container-cli: initialization error: driver error: failed to process request\\\\n\\\"\"": unknown.
```
- You switched the name from audiodetection.md to readme.md
- Command 47 in your jupyter notebook has the output `/bin/sh: 1: nvidia-docker: not found` is the the right output?
- At the end of the Jupyter notebook can you add cells to include eval.y and inference.py with a test wav file?

**Comment by yradsmikham** [comment]
Finalized version of the Jupyter notebook!

**Comment by yradsmikham** [comment]
Oops, accidentally hit closed! Apologies.

**Comment by NathanielRose** [comment]
Looks Good!

**Pull request merged**
